// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/processor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessRequest contains the raw image data to be processed.
type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_proto_v1_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ProcessResponse contains the optimized image data.
type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_v1_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_v1_processor_proto protoreflect.FileDescriptor

const file_proto_v1_processor_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/processor.proto\x12\tgatuno.v1\"$\n" +
	"\x0eProcessRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fProcessResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2R\n" +
	"\x0eImageProcessor\x12@\n" +
	"\aProcess\x12\x19.gatuno.v1.ProcessRequest\x1a\x1a.gatuno.v1.ProcessResponseB5Z3github.com/luis/file-processor/internal/api/grpc/pbb\x06proto3"

var (
	file_proto_v1_processor_proto_rawDescOnce sync.Once
	file_proto_v1_processor_proto_rawDescData []byte
)

func file_proto_v1_processor_proto_rawDescGZIP() []byte {
	file_proto_v1_processor_proto_rawDescOnce.Do(func() {
		file_proto_v1_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_processor_proto_rawDesc), len(file_proto_v1_processor_proto_rawDesc)))
	})
	return file_proto_v1_processor_proto_rawDescData
}

var file_proto_v1_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_processor_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: gatuno.v1.ProcessRequest
	(*ProcessResponse)(nil), // 1: gatuno.v1.ProcessResponse
}
var file_proto_v1_processor_proto_depIdxs = []int32{
	0, // 0: gatuno.v1.ImageProcessor.Process:input_type -> gatuno.v1.ProcessRequest
	1, // 1: gatuno.v1.ImageProcessor.Process:output_type -> gatuno.v1.ProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_processor_proto_init() }
func file_proto_v1_processor_proto_init() {
	if File_proto_v1_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_processor_proto_rawDesc), len(file_proto_v1_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_processor_proto_goTypes,
		DependencyIndexes: file_proto_v1_processor_proto_depIdxs,
		MessageInfos:      file_proto_v1_processor_proto_msgTypes,
	}.Build()
	File_proto_v1_processor_proto = out.File
	file_proto_v1_processor_proto_goTypes = nil
	file_proto_v1_processor_proto_depIdxs = nil
}
