// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: proto/v1/processor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessRequest contains the raw image data to be processed.
type ProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional widths (in pixels) for additional smaller renditions to
	// generate alongside the primary output. Opt-in: empty means no variants.
	// Capped server-side (see internal/processor.MaxVariantWidths); rejected
	// entirely for images taller than the split threshold, since splitting and
	// variants are mutually exclusive.
	Widths []int32 `protobuf:"varint,2,rep,packed,name=widths,proto3" json:"widths,omitempty"`
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessRequest) GetWidths() []int32 {
	if x != nil {
		return x.Widths
	}
	return nil
}

// ProcessedImage is one output image: either the primary conversion, a
// tall-image split part, or a smaller variant.
type ProcessedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// "original", "part", or "variant" — see internal/processor.Kind*.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Width in pixels of this specific output. Always populated.
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *ProcessedImage) Reset() {
	*x = ProcessedImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedImage) ProtoMessage() {}

func (x *ProcessedImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedImage.ProtoReflect.Descriptor instead.
func (*ProcessedImage) Descriptor() ([]byte, []int) {
	return file_proto_v1_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessedImage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessedImage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProcessedImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

// ProcessResponse contains the optimized image(s).
type ProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: use results[0].data instead. Retained for one release so
	// existing callers keep working; always mirrors the "original" image.
	//
	// Deprecated: Marked as deprecated in proto/v1/processor.proto.
	Data    []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Results []*ProcessedImage `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_processor_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in proto/v1/processor.proto.
func (x *ProcessResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessResponse) GetResults() []*ProcessedImage {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_v1_processor_proto protoreflect.FileDescriptor

var file_proto_v1_processor_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x61, 0x74, 0x75,
	0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x3c, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x73, 0x22, 0x4e, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x22, 0x5e, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x33,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x61, 0x74, 0x75, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x32, 0x52, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x19, 0x2e, 0x67, 0x61, 0x74, 0x75, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61,
	0x74, 0x75, 0x6e, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x69, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2d,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_processor_proto_rawDescOnce sync.Once
	file_proto_v1_processor_proto_rawDescData = file_proto_v1_processor_proto_rawDesc
)

func file_proto_v1_processor_proto_rawDescGZIP() []byte {
	file_proto_v1_processor_proto_rawDescOnce.Do(func() {
		file_proto_v1_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_processor_proto_rawDescData)
	})
	return file_proto_v1_processor_proto_rawDescData
}

var file_proto_v1_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_processor_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: gatuno.v1.ProcessRequest
	(*ProcessedImage)(nil),  // 1: gatuno.v1.ProcessedImage
	(*ProcessResponse)(nil), // 2: gatuno.v1.ProcessResponse
}
var file_proto_v1_processor_proto_depIdxs = []int32{
	1, // 0: gatuno.v1.ProcessResponse.results:type_name -> gatuno.v1.ProcessedImage
	0, // 1: gatuno.v1.ImageProcessor.Process:input_type -> gatuno.v1.ProcessRequest
	2, // 2: gatuno.v1.ImageProcessor.Process:output_type -> gatuno.v1.ProcessResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_processor_proto_init() }
func file_proto_v1_processor_proto_init() {
	if File_proto_v1_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_processor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_processor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessedImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_processor_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_processor_proto_goTypes,
		DependencyIndexes: file_proto_v1_processor_proto_depIdxs,
		MessageInfos:      file_proto_v1_processor_proto_msgTypes,
	}.Build()
	File_proto_v1_processor_proto = out.File
	file_proto_v1_processor_proto_rawDesc = nil
	file_proto_v1_processor_proto_goTypes = nil
	file_proto_v1_processor_proto_depIdxs = nil
}
